import Head from "next/head";
import styles from "../styles/Home.module.css";
import client from "../apollo-client";
import { gql } from "@apollo/client";
import { useState } from "react";

export async function getServerSideProps() {
  const { data } = await client.query({
    query: gql`
      query getBlogBySlug {
        blogPosts(stage: PUBLISHED) {
          slug
          blogContent {
            title
            author {
              name
              username
            }
            popularity
          }
        }
      }
    `,
  });
  return {
    props: data,
  };
}

export default function Home({ blogPosts }) {
  const [slug, setSlug] = useState("");

  async function addBlog() {
    await fetch("/api/addBlogPost", {
      method: "POST",
      headers: {
        "content-type": "application/json",
      },
      body: JSON.stringify({ slug }),
    });
    setSlug("");
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Add blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <input
        placeholder={"Blog slug"}
        value={slug}
        onChange={(e) => setSlug(e.target.value)}
      />
      <button onClick={addBlog}>Add blog</button>
      {blogPosts.length ? (
        <ul>
          {blogPosts.map((blog) => (
            <li key={blog.slug}>{blog.blogContent.title}</li>
          ))}
        </ul>
      ) : null}
    </div>
  );
}
